### ISSUE TITLE
[Crash issue] 실시간 교통정보 표출 후 맵 스크롤 시 crash 

### ISSUE THREAD

**Issue by jw-choi-hyundai** [PlayMap-HMNS/Playmap-developers#12]
- 아래와 같이 Map init이 끝난 시점에 setMapTraffic을 한 후 지도를 scroll하게 되면 crash 발생되고 있습니다.

[소스]
`        mMapView.onMapInitListener(new PlayMapView.OnMapInitCallback() {
            @Override
            public void onMapInitEvent(int i, PlayMapPoint playMapPoint) {
                initUI();
                mMapView.setMapTraffic(true);
            }
        });
`

[Log]
2020-11-26 11:40:21.729 26791-26791/com.playmap.playmapdev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.playmap.playmapdev, PID: 26791
    com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source trafficSource9 already exists
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:858)
        at com.mapbox.mapboxsdk.maps.Style.addSource(Style.java:117)
        at com.hmns.playmap.PlayMapView$14$1$1$1.run(PlayMapView.java:2275)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Playmap-HAE** [comment]
안녕하세요. PlayMap입니다.

최근 인증방식의 변경으로 인하여 Android SDK 최신 버전이 금일 업로드 되었습니다.
번거로우시겠지만 최신 버전 SDK를 다운로드 후 교통정보 재시도 부탁드립니다.

1. Project > app > libs 파일 내 aar 파일을 붙여넣은 후 
2. build.gradle aar 파일명 변경

dependencies {

    implementation 'com.facebook.soloader:soloader:0.6.0+'
    implementation name: 'PlayMapSDK_1.1', ext: 'aar'

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

3. Gradle Sync 
4. App Build

감사합니다.

**Comment by jw-choi-hyundai** [comment]
SDK 변경 후에도 Crash 발생됩니다.
재확인 부탁드립니다.

2020-11-27 11:31:00.987 10572-10572/com.playmap.playmapdev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.playmap.playmapdev, PID: 10572
    com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source trafficSource1 already exists
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:858)
        at com.mapbox.mapboxsdk.maps.Style.addSource(Style.java:117)
        at com.hmns.playmap.PlayMapView$14$1$1$1.run(PlayMapView.java:2288)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by jw-choi-hyundai** [comment]
playmap sdk 1.2 변경시에도 아래와 같은 crash 발생하고 있습니다.

2020-12-16 11:52:17.217 25006-25006/com.playmap.playmapdev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.playmap.playmapdev, PID: 25006
    com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source trafficSource8 already exists
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:858)
        at com.mapbox.mapboxsdk.maps.Style.addSource(Style.java:117)
        at com.hmns.playmap.PlayMapView$14$1$1$1.run(PlayMapView.java:2288)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
