### ISSUE TITLE
mapView oncreate Crash 이슈

### ISSUE THREAD

**Issue by jw-choi-hyundai** [PlayMap-HMNS/Playmap-developers#6]
key값을 넣었는데도 아래와 같이 exception이 나서 죽고 있습니다.
소스는 developer site와 동일하게 진행했습니다.

[소스]
//RestAPI 권한
        mapRestApi = new PlayMapRestApi(mContext);
        mapRestApi.setPlayMapApiKey("*********");
        
        // 지도 생성
        PlayMapView mapView;
        mapView = new PlayMapView(this); //여기서 mapView null
        mapView = findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);

        // 지도 생성시 중심점 좌표 설정
        mapView.initMap(37.56640, 126.97851, 17);

[로그]
2020-11-23 17:51:30.177 18634-18634/com.playmap.playmapdev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.playmap.playmapdev, PID: 18634
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.playmap.playmapdev/com.playmap.playmapdev.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.hmns.playmap.PlayMapView.onCreate(android.os.Bundle)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.hmns.playmap.PlayMapView.onCreate(android.os.Bundle)' on a null object reference
        at com.playmap.playmapdev.MainActivity.onCreate(MainActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:7995)
        at android.app.Activity.performCreate(Activity.java:7979)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Playmap-HAE** [comment]
@jw-choi-hyundai 

SDK 시작하기 가이드가 부족하여 발생한 문제인것 같습니다.
Layout에 mapView를 다음과 같이 선언 되었는지 확인 부탁드립니다.

![sample이미지](https://user-images.githubusercontent.com/58937810/100044423-02daf780-2e53-11eb-916c-6c38eb45d947.png)

**Comment by jw-choi-hyundai** [comment]
이슈 해결 되었습니다 :)
가이드에도 넣어주시면 감사하겠습니다.

감사합니다!

**Comment by Playmap-HAE** [comment]
@jw-choi-hyundai 
일단 API 키부분은 다른 사람에게도 노출될 수 있어 *****처리 하였습니다.
