### ISSUE TITLE
[Crash issue] setMapRotation Crash error!

### ISSUE THREAD

**Issue by jw-choi-hyundai** [PlayMap-HMNS/Playmap-developers#7]
아래와 같이 PlayMapView에 setMapRotation을 하면 죽네요..
setting 방법이 따로 있는지요?

[소스]
        mMapView.setMapRotate(true);
        mMapView.setCompassMode(true);

[이슈]
2020-11-24 17:16:51.859 3210-3210/com.playmap.playmapdev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.playmap.playmapdev, PID: 3210
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.playmap.playmapdev/com.playmap.playmapdev.MapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxsdk.maps.UiSettings com.mapbox.mapboxsdk.maps.MapboxMap.getUiSettings()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     **Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxsdk.maps.UiSettings com.mapbox.mapboxsdk.maps.MapboxMap.getUiSettings()' on a null object reference**
        at com.hmns.playmap.PlayMapView.setMapRotate(PlayMapView.java:908)
        at com.playmap.playmapdev.MapActivity.initUI(MapActivity.java:66)
        at com.playmap.playmapdev.MapActivity.onCreate(MapActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:7995)
        at android.app.Activity.performCreate(Activity.java:7979)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Playmap-HAE** [comment]
안녕하세요. PlayMap입니다.

지도 로딩 전에 setMapRotation가 호출되어 발생한 오류입니다.
지도 로딩 이후 setMapRotation가 호출되면 정상적으로 동작됩니다.

다음과 같이 지도 로딩 후 호출되는 Listener에서 셋팅을 참고하시거나 
버튼과 같이 특정 이벤트 호출 시 setMapRotation를 셋팅하시면 됩니다.

// 지도 로딩 후 호출 Listener
mapView.onMapInitListener(new PlayMapView.OnMapInitCallback() {
	@Override
	public void onMapInitEvent(int zoom, PlayMapPoint playMapPoint) {
		mapView.setMapRotate(true);
                mapView.setCompassMode(true);
	}
});

**Comment by jw-choi-hyundai** [comment]
지도 로딩 후 event에 동작시 정상 동작
